// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: internal/proto/wireguard.proto

package gen_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IP       string `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_wireguard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wireguard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_wireguard_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectResponse) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *ConnectResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ConfigName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfName string `protobuf:"bytes,1,opt,name=conf_name,json=confName,proto3" json:"conf_name,omitempty"`
}

func (x *ConfigName) Reset() {
	*x = ConfigName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_wireguard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigName) ProtoMessage() {}

func (x *ConfigName) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wireguard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigName.ProtoReflect.Descriptor instead.
func (*ConfigName) Descriptor() ([]byte, []int) {
	return file_internal_proto_wireguard_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigName) GetConfName() string {
	if x != nil {
		return x.ConfName
	}
	return ""
}

type AddConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigId      *ConfigID      `protobuf:"bytes,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	ConfigAddress *ConfigAddress `protobuf:"bytes,2,opt,name=config_address,json=configAddress,proto3" json:"config_address,omitempty"`
}

func (x *AddConfigResponse) Reset() {
	*x = AddConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_wireguard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddConfigResponse) ProtoMessage() {}

func (x *AddConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wireguard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddConfigResponse.ProtoReflect.Descriptor instead.
func (*AddConfigResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_wireguard_proto_rawDescGZIP(), []int{2}
}

func (x *AddConfigResponse) GetConfigId() *ConfigID {
	if x != nil {
		return x.ConfigId
	}
	return nil
}

func (x *AddConfigResponse) GetConfigAddress() *ConfigAddress {
	if x != nil {
		return x.ConfigAddress
	}
	return nil
}

type ConfigIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigId *ConfigID `protobuf:"bytes,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
}

func (x *ConfigIdResponse) Reset() {
	*x = ConfigIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_wireguard_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigIdResponse) ProtoMessage() {}

func (x *ConfigIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wireguard_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigIdResponse.ProtoReflect.Descriptor instead.
func (*ConfigIdResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_wireguard_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigIdResponse) GetConfigId() *ConfigID {
	if x != nil {
		return x.ConfigId
	}
	return nil
}

type GetConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Enabled             bool   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Address             string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	PublicKey           string `protobuf:"bytes,5,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	CreatedAt           string `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt           string `protobuf:"bytes,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	PersistentKeepalive string `protobuf:"bytes,8,opt,name=persistentKeepalive,proto3" json:"persistentKeepalive,omitempty"`
	LatestHandshakeAt   string `protobuf:"bytes,9,opt,name=latestHandshakeAt,proto3" json:"latestHandshakeAt,omitempty"`
	TransferRx          int64  `protobuf:"varint,10,opt,name=transferRx,proto3" json:"transferRx,omitempty"`
	TransferTx          int64  `protobuf:"varint,11,opt,name=transferTx,proto3" json:"transferTx,omitempty"`
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_wireguard_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wireguard_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_wireguard_proto_rawDescGZIP(), []int{4}
}

func (x *GetConfigResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetConfigResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetConfigResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GetConfigResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetConfigResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *GetConfigResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetConfigResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *GetConfigResponse) GetPersistentKeepalive() string {
	if x != nil {
		return x.PersistentKeepalive
	}
	return ""
}

func (x *GetConfigResponse) GetLatestHandshakeAt() string {
	if x != nil {
		return x.LatestHandshakeAt
	}
	return ""
}

func (x *GetConfigResponse) GetTransferRx() int64 {
	if x != nil {
		return x.TransferRx
	}
	return 0
}

func (x *GetConfigResponse) GetTransferTx() int64 {
	if x != nil {
		return x.TransferTx
	}
	return 0
}

type GetAllConfigsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfList []*GetConfigResponse `protobuf:"bytes,1,rep,name=conf_list,json=confList,proto3" json:"conf_list,omitempty"`
}

func (x *GetAllConfigsResponse) Reset() {
	*x = GetAllConfigsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_wireguard_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllConfigsResponse) ProtoMessage() {}

func (x *GetAllConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wireguard_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllConfigsResponse.ProtoReflect.Descriptor instead.
func (*GetAllConfigsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_wireguard_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllConfigsResponse) GetConfList() []*GetConfigResponse {
	if x != nil {
		return x.ConfList
	}
	return nil
}

type ConfigID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfId string `protobuf:"bytes,1,opt,name=conf_id,json=confId,proto3" json:"conf_id,omitempty"`
}

func (x *ConfigID) Reset() {
	*x = ConfigID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_wireguard_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigID) ProtoMessage() {}

func (x *ConfigID) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wireguard_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigID.ProtoReflect.Descriptor instead.
func (*ConfigID) Descriptor() ([]byte, []int) {
	return file_internal_proto_wireguard_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigID) GetConfId() string {
	if x != nil {
		return x.ConfId
	}
	return ""
}

type ConfigAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfAddress string `protobuf:"bytes,1,opt,name=conf_address,json=confAddress,proto3" json:"conf_address,omitempty"`
}

func (x *ConfigAddress) Reset() {
	*x = ConfigAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_wireguard_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigAddress) ProtoMessage() {}

func (x *ConfigAddress) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wireguard_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigAddress.ProtoReflect.Descriptor instead.
func (*ConfigAddress) Descriptor() ([]byte, []int) {
	return file_internal_proto_wireguard_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigAddress) GetConfAddress() string {
	if x != nil {
		return x.ConfAddress
	}
	return ""
}

type ConfigAmount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount int32 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *ConfigAmount) Reset() {
	*x = ConfigAmount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_wireguard_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigAmount) ProtoMessage() {}

func (x *ConfigAmount) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wireguard_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigAmount.ProtoReflect.Descriptor instead.
func (*ConfigAmount) Descriptor() ([]byte, []int) {
	return file_internal_proto_wireguard_proto_rawDescGZIP(), []int{8}
}

func (x *ConfigAmount) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type QRCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QrCode []byte `protobuf:"bytes,1,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
}

func (x *QRCode) Reset() {
	*x = QRCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_wireguard_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QRCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QRCode) ProtoMessage() {}

func (x *QRCode) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wireguard_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QRCode.ProtoReflect.Descriptor instead.
func (*QRCode) Descriptor() ([]byte, []int) {
	return file_internal_proto_wireguard_proto_rawDescGZIP(), []int{9}
}

func (x *QRCode) GetQrCode() []byte {
	if x != nil {
		return x.QrCode
	}
	return nil
}

type ConfigText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ConfigText) Reset() {
	*x = ConfigText{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_wireguard_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigText) ProtoMessage() {}

func (x *ConfigText) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wireguard_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigText.ProtoReflect.Descriptor instead.
func (*ConfigText) Descriptor() ([]byte, []int) {
	return file_internal_proto_wireguard_proto_rawDescGZIP(), []int{10}
}

func (x *ConfigText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_internal_proto_wireguard_proto protoreflect.FileDescriptor

var file_internal_proto_wireguard_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x77, 0x69, 0x72, 0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3d, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x22, 0x29, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x66, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x80, 0x01, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x44, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0x41, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x44, 0x52, 0x08, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x49, 0x64, 0x22, 0xe5, 0x02, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x30, 0x0a,
	0x13, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x65, 0x70, 0x61,
	0x6c, 0x69, 0x76, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x70, 0x65, 0x72, 0x73,
	0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x4b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x12,
	0x2c, 0x0a, 0x11, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61,
	0x6b, 0x65, 0x41, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x6c, 0x61, 0x74, 0x65,
	0x73, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x41, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x78, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x78, 0x12, 0x1e, 0x0a,
	0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x54, 0x78, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x54, 0x78, 0x22, 0x4f, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x66, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x23,
	0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x44, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x66,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x26, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x21, 0x0a, 0x06, 0x51, 0x52, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x71, 0x72, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x71, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x22, 0x20, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x54, 0x65, 0x78, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x32, 0xda, 0x04, 0x0a, 0x09, 0x57, 0x69, 0x72, 0x65, 0x67, 0x75, 0x61,
	0x72, 0x64, 0x12, 0x3a, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x17, 0x2e,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3a,
	0x0a, 0x09, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x2e, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x1a,
	0x19, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x44, 0x12, 0x15, 0x2e, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x1a, 0x18, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x10, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x44, 0x1a, 0x12, 0x2e, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x54, 0x65, 0x78, 0x74, 0x12, 0x46, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1d, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x73, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x14, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x39, 0x0a, 0x0d, 0x44, 0x69, 0x73, 0x61, 0x62,
	0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x10, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x44, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x38, 0x0a, 0x0c, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x10, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x49, 0x44, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x38, 0x0a, 0x0c,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x10, 0x2e, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x44, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x29, 0x0a, 0x05, 0x47, 0x65, 0x74, 0x51, 0x52, 0x12,
	0x10, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49,
	0x44, 0x1a, 0x0e, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x2e, 0x51, 0x52, 0x43, 0x6f, 0x64,
	0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x67, 0x65, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_wireguard_proto_rawDescOnce sync.Once
	file_internal_proto_wireguard_proto_rawDescData = file_internal_proto_wireguard_proto_rawDesc
)

func file_internal_proto_wireguard_proto_rawDescGZIP() []byte {
	file_internal_proto_wireguard_proto_rawDescOnce.Do(func() {
		file_internal_proto_wireguard_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_wireguard_proto_rawDescData)
	})
	return file_internal_proto_wireguard_proto_rawDescData
}

var file_internal_proto_wireguard_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_proto_wireguard_proto_goTypes = []any{
	(*ConnectResponse)(nil),       // 0: stores.ConnectResponse
	(*ConfigName)(nil),            // 1: stores.ConfigName
	(*AddConfigResponse)(nil),     // 2: stores.AddConfigResponse
	(*ConfigIdResponse)(nil),      // 3: stores.ConfigIdResponse
	(*GetConfigResponse)(nil),     // 4: stores.GetConfigResponse
	(*GetAllConfigsResponse)(nil), // 5: stores.GetAllConfigsResponse
	(*ConfigID)(nil),              // 6: stores.ConfigID
	(*ConfigAddress)(nil),         // 7: stores.ConfigAddress
	(*ConfigAmount)(nil),          // 8: stores.ConfigAmount
	(*QRCode)(nil),                // 9: stores.QRCode
	(*ConfigText)(nil),            // 10: stores.ConfigText
	(*emptypb.Empty)(nil),         // 11: google.protobuf.Empty
}
var file_internal_proto_wireguard_proto_depIdxs = []int32{
	6,  // 0: stores.AddConfigResponse.config_id:type_name -> stores.ConfigID
	7,  // 1: stores.AddConfigResponse.config_address:type_name -> stores.ConfigAddress
	6,  // 2: stores.ConfigIdResponse.config_id:type_name -> stores.ConfigID
	4,  // 3: stores.GetAllConfigsResponse.conf_list:type_name -> stores.GetConfigResponse
	0,  // 4: stores.Wireguard.Connect:input_type -> stores.ConnectResponse
	1,  // 5: stores.Wireguard.AddConfig:input_type -> stores.ConfigName
	7,  // 6: stores.Wireguard.GetConfigID:input_type -> stores.ConfigAddress
	6,  // 7: stores.Wireguard.GetConfig:input_type -> stores.ConfigID
	11, // 8: stores.Wireguard.GetAllConfigs:input_type -> google.protobuf.Empty
	11, // 9: stores.Wireguard.GetConfigsAmount:input_type -> google.protobuf.Empty
	6,  // 10: stores.Wireguard.DisableConfig:input_type -> stores.ConfigID
	6,  // 11: stores.Wireguard.EnableConfig:input_type -> stores.ConfigID
	6,  // 12: stores.Wireguard.DeleteConfig:input_type -> stores.ConfigID
	6,  // 13: stores.Wireguard.GetQR:input_type -> stores.ConfigID
	11, // 14: stores.Wireguard.Connect:output_type -> google.protobuf.Empty
	2,  // 15: stores.Wireguard.AddConfig:output_type -> stores.AddConfigResponse
	3,  // 16: stores.Wireguard.GetConfigID:output_type -> stores.ConfigIdResponse
	10, // 17: stores.Wireguard.GetConfig:output_type -> stores.ConfigText
	5,  // 18: stores.Wireguard.GetAllConfigs:output_type -> stores.GetAllConfigsResponse
	8,  // 19: stores.Wireguard.GetConfigsAmount:output_type -> stores.ConfigAmount
	11, // 20: stores.Wireguard.DisableConfig:output_type -> google.protobuf.Empty
	11, // 21: stores.Wireguard.EnableConfig:output_type -> google.protobuf.Empty
	11, // 22: stores.Wireguard.DeleteConfig:output_type -> google.protobuf.Empty
	9,  // 23: stores.Wireguard.GetQR:output_type -> stores.QRCode
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_internal_proto_wireguard_proto_init() }
func file_internal_proto_wireguard_proto_init() {
	if File_internal_proto_wireguard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_wireguard_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ConnectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_wireguard_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_wireguard_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*AddConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_wireguard_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_wireguard_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_wireguard_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllConfigsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_wireguard_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_wireguard_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_wireguard_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigAmount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_wireguard_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*QRCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_wireguard_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigText); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_wireguard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_wireguard_proto_goTypes,
		DependencyIndexes: file_internal_proto_wireguard_proto_depIdxs,
		MessageInfos:      file_internal_proto_wireguard_proto_msgTypes,
	}.Build()
	File_internal_proto_wireguard_proto = out.File
	file_internal_proto_wireguard_proto_rawDesc = nil
	file_internal_proto_wireguard_proto_goTypes = nil
	file_internal_proto_wireguard_proto_depIdxs = nil
}
